In [ ]:
#| default_exp core

# module name here

> API details.

In [ ]:
#|hide
from nbdev.showdoc import *
import akshare as ak
import numpy as np

In [ ]:
#|export

def build_future_maxmin_idx_ds(stock_code, maxmin_period=90):
    hist = ak.stock_zh_index_daily(symbol=stock_code)
    print(len(hist))
    ds = hist.iloc[:-maxmin_period, :]
    print(len(ds))
    
    future_max = [None] * (len(ds))
    future_max_pos = [None] * (len(ds))
    future_min = [None] * (len(ds))
    future_min_pos = [None] * (len(ds))
    
    for pointer in np.arange(len(hist)-maxmin_period):
        future_segment = hist.iloc[pointer+1:pointer+maxmin_period, :]
        
        future_max[pointer] = future_segment['high'].max()
        future_max_pos[pointer] = future_segment['high'].argmax()
        
        future_min[pointer] = future_segment['low'].min()
        future_min_pos[pointer] = future_segment['low'].argmin()     
    
    ds['future_range_max'] = future_max
    ds['future_range_max_pos'] = future_max_pos
    
    ds['future_range_min'] = future_min
    ds['future_range_min_pos'] = future_min_pos
    
    
    return ds

In [ ]:
#| hide
hist = build_future_maxmin_idx_ds(stock_code='sh000001', maxmin_period=90)
hist.tail()

7734
7644

/tmp/ipykernel_82234/3793680348.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['future_range_max'] = future_max
/tmp/ipykernel_82234/3793680348.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['future_range_max_pos'] = future_max_pos
/tmp/ipykernel_82234/3793680348.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['future_range_min'] = future_min
/tmp/ipykernel_82234/3793680348.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds['future_range_min_pos'] = future_min_pos

,date,open,high,low,close,volume,future_range_max,future_range_max_pos,future_range_min,future_range_min_pos
7639,2022-03-25,3247.157,3257.106,3211.645,3212.240,34002000600,3424.837,7704,2863.65,7659
7640,2022-03-28,3185.167,3230.215,3159.835,3214.503,34499487300,3424.837,7704,2863.65,7659
7641,2022-03-29,3216.012,3229.177,3196.455,3203.939,31627364900,3424.837,7704,2863.65,7659
7642,2022-03-30,3217.592,3266.596,3216.302,3266.596,36675367700,3424.837,7704,2863.65,7659
7643,2022-03-31,3256.137,3272.040,3246.063,3252.203,39843993400,3424.837,7704,2863.65,7659

In [ ]:
#|export
def hello(): 
    print('Hello, StreamTSAI!')